### ISSUE TITLE
Check Telemetrum battery connector

### ISSUE THREAD

**Issue by ghost** [psas/Launch-12#17]
During aeroshell removal post Launch 11, a connector showed damage or was at least disturbed on one of the COTS flight computers (_the TeleMetrum? Confirmation needed._). It is **_not**_ clear whether this was due to action during:
- aeroshell removal
- during aeroshell assembly 
- some other mechanism to be determined

In any case, this may indicate there is not enough clearance between the aeroshell and the electronics and wire harnesses in the module.

**Comment by andrewgreenberg** [comment]
Telemetrum battery connector was whacked while removing the payload module's aeroshell. The aeroshell was impossible to remove because some idiot (probably me) left blue tape on the side of the module :(

So, the real issue here: I field repaired the connector, but it should be carefully examined before next ues.

**Comment by andrewgreenberg** [comment]
Hey Dave, please check this. If necessary, assign to me and I'll do it after you're up and running.

**Comment by dsigma** [comment]
I checked the connectors on both TM's and all 3 batteries. TM connections look great, the crimp-on connections that are on the batteries are nicely clamping on the insulation of the respective wires and look clean and solid. Closing this ticket.
