### ISSUE TITLE
Rocket Rack truck side bed mounts

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#29]
We'd like a mechanism that could attach to the tie points on the top of the truck bed, and allow the rocket rack to mount in, to simplify moving the rocket up to the tower.

**Comment by LateralGs** [comment]
I think this could be made using plywood that has a V in it for the rocket to sit along with two holes that can be used to bolt it to your tie downs.  This could be easily cut with a jig saw and hand drill.  Foam pipe insulation makes for good cushions for the rocket to sit on.  Who ever makes this needs to keep in mind that we will have larger diameter airframes in the future and to make sure the supports account for this (ie. make it a V with a curved bottom instead of a U ).  Also having holes for tie downs is a plus.  Crappy design image attached.
![truck_rocket_holder](https://cloud.githubusercontent.com/assets/5344225/3698107/1934eeca-13b9-11e4-8982-f507951940a7.png)

**Comment by dsigma** [comment]
As an alternate idea, what if we used the carrying poles, which will probably be like 8ft wide, and put the rocket in the truck length wise, with the poles going over the walls of the truck, and each end of the pole clipping to the tie-downs on the bed of the truck. This would also give some mechanical damping to the rocket as it could swing a little under the poles as we're driving up to the hill. Also, if we used the poles to help load it on the rail, it would already be attached to the poles?

thoughts?

**Comment by LateralGs** [comment]
Can you post the dimensions of the bed of your truck along with the locations and dimensions of the tie downs?

**Comment by dsigma** [comment]
The distance between the inside edge of the truck bed walls is 61.75". Other dimensions are in the pictures I gave you.

**Comment by natronics** [comment]
Dave made this!

**Comment by dsigma** [comment]
I made something different...

**Comment by LateralGs** [comment]
I present to you some mobile rocket stands that can be used in the truck, on the ground, or even on a table.  These break down to be packed flat.  Should work well enough in the truck for recovery and at the tower.

![mobile_rocket_stand](https://cloud.githubusercontent.com/assets/5344225/8515861/2958bc7a-2360-11e5-8119-631591c7a901.JPG)
![mobile_rocket_stand_apart](https://cloud.githubusercontent.com/assets/5344225/8515862/29693bfe-2360-11e5-8c9b-5a71b760993c.JPG)

If this is acceptable then this ticket can be closed.

**Comment by dsigma** [comment]
Love it!
