### ISSUE TITLE
Order more J-Tek E-Matches

### ISSUE THREAD

**Issue by dsigma** [psas/Launch-12#57]
We're down to 7, and we need 6 per launch (4 for the NSR, 2 for the line cutters)

**Comment by dsigma** [comment]
@andrewgreenberg, can you order these?

**Comment by andrewgreenberg** [comment]
@dsigma: kind of? My ATF license has long since expired, so I can't order J-TEKs. Luckily MJG now has an unlicensed brand of ematches: https://electricmatch.com/products/see/6/mjg-firewire-initiator

They look exactly similar, and have extremely similar characteristics:

```
 Igniter type                        Firewire      J-TEK
 Bridgewire Resistance               1± 0.2 ohms    1± 0.2 ohms
 Maximum No-Fire Current              300 mA        300 mA
 Minimum All-Fire Current             600 mA        750 mA
 Recommended Minimum Firing Current   750 mA       1.00 A
 Recommended Nominal Firing Current  1.00 A        1.25 A
 Maximum Test Current                  40 mA         40 mA
```

... so I believe they're a direct 1:1 replacement for the J-TEK. Closing this issue!

**Comment by dsigma** [comment]
I don't like the idea of doing a last minute swap of e-matches on a system as critical as recovery. The electrical properties may be the same, but how about the thermal and burn properties? I'd rather use J-Tek's if we can find them locally. I'll ask around...

**Comment by andrewgreenberg** [comment]
Again, I'm not really worried about this because it's so clearly the same thing. That said, please do ask around. It may be that some OROC members have spare J-TEKs, and we only need 6 more for this project. Sorry I can't be more helpful.
