### ISSUE TITLE
Update the Raspicam2 with new gstreamer scripts

### ISSUE THREAD

**Issue by vosechu** [psas/Launch-12#64]
- install via apt-get
- update go_cameras_go.sh
- remove entries from rc.local
- test

**Comment by vosechu** [comment]
Also, get these into the psas/flight-director-table

**Comment by aSmig** [comment]
Since picam2 is only recording video and not streaming it, we don't need gstreamer there.  But updating all the go_cameras_go.sh stuff to create a video file when triggered by camera-automation was needed.  Looks like it starts up in a good state and is ready for launch.  Presently recording at 720p.
